import { FC, ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import TRPCProvider from "./_trpc/provider";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import NextUIProvider from "@/components/NextUIProvider";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <TRPCProvider cookies={cookies().toString()}>
            <NextUIProvider>
            <ThemeProvider>

            {children}
            </ThemeProvider>
            </NextUIProvider>
          </TRPCProvider>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
